### ISSUE TITLE
--fks errors on second run against same database

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-generate#10]
```
$ sqlite-generate % sqlite-generate data.db
Generating rows  [####################################]  1035/1035  100%
Populating foreign keys  [###########-------------------------]  7/22   31%
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/sqlite-generate-_TC9iTyA/bin/sqlite-generate", line 11, in <module>
    load_entry_point('sqlite-generate', 'console_scripts', 'sqlite-generate')()
  File "/Users/simon/.local/share/virtualenvs/sqlite-generate-_TC9iTyA/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/sqlite-generate-_TC9iTyA/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/sqlite-generate-_TC9iTyA/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/sqlite-generate-_TC9iTyA/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/sqlite-generate/sqlite_generate/cli.py", line 113, in cli
    db[table_name].add_foreign_key(column, other_table, "id")
  File "/Users/simon/.local/share/virtualenvs/sqlite-generate-_TC9iTyA/lib/python3.8/site-packages/sqlite_utils/db.py", line 756, in add_foreign_key
    raise AlterError(
sqlite_utils.db.AlterError: Foreign key already exists for return_id => result_beautiful_responsibility.id
```

**Comment by simonw** [comment]
That's because this code here considers ALL tables, not just the tables that were created by the second run of the tool: https://github.com/simonw/sqlite-generate/blob/cfa90baeaff161e8b4aa303021784783ff426b3d/sqlite_generate/cli.py#L89-L96
